export const TOGGLE_PLAY = 'TOGGLE_PLAY';
export const VIDEO_TIME_CHANGE = 'VIDEO_TIME_CHANGE';
export const ADD_VIDEO_DURATION = 'ADD_VIDEO_DURATION';
export const ADD_CLIP = 'ADD_CLIP';
export const EDIT_CLIP = 'EDIT_CLIP';
export const REMOVE_CLIP = 'REMOVE_CLIP';
export const SET_CURRENT_CLIP = 'SET_CURRENT_CLIP';
export const REMOVE_CURRENT_CLIP = 'REMOVE_CURRENT_CLIP';
